# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  OpenWrt_OS: immortalwrt
  OS_BRANCH: main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
 
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Lienol openwrt 1
        if: env.OpenWrt_OS == 'Lienol' && env.OS_BRANCH == ''
        run: |
          echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=21.02" >> $GITHUB_ENV
          echo "DIR_NAME=openwrt" >> $GITHUB_ENV
      
      - name: Lienol openwrt 2
        if: env.OpenWrt_OS == 'Lienol' && env.OS_BRANCH != ''
        run: |
          echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=${{env.OS_BRANCH}}" >> $GITHUB_ENV
          echo "DIR_NAME=openwrt" >> $GITHUB_ENV

      - name: coolsnowwolf lede 
        if: env.OpenWrt_OS == 'Lean'
        run: |
          echo "REPO_URL=https://github.com/coolsnowwolf/lede" >> $GITHUB_ENV
          echo "REPO_BRANCH=master" >> $GITHUB_ENV
          echo "DIR_NAME=lean" >> $GITHUB_ENV
      
      - name: 天灵 immortalwrt 1
        if: env.OpenWrt_OS == 'immortalwrt' && env.OS_BRANCH == ''
        run: |
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=openwrt-18.06-k5.4" >> $GITHUB_ENV
          echo "DIR_NAME=immortalwrt" >> $GITHUB_ENV
      
      - name: 天灵 immortalwrt 2
        if: env.OpenWrt_OS == 'immortalwrt' && env.OS_BRANCH != ''
        run: |
          echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV
          echo "REPO_BRANCH=${{env.OS_BRANCH}}" >> $GITHUB_ENV
          echo "DIR_NAME=immortalwrt" >> $GITHUB_ENV
          
      - name: Lienol ck
        run: |
          echo "你好"

