

name: CI


on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


  workflow_dispatch:
env:
  OpenWtr_OS: Lienol
  OS_BRANCH: ''



jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3


      - name: Run a one-line script
        run: echo Hello, world!


      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

    - name: Lienol openwrt
       if: env.OpenWtr_OS == 'Lienol'
       echo "REPO_URL=https://github.com/Lienol/openwrt" >> $GITHUB_ENV
       if: env.OpenWtr_OS == 'Lienol' && env.OS_BRANCH != ''
       echo "REPO_BRANCH=$({{OS_BRANCH}})" >> $GITHUB_ENV
       if: env.OpenWtr_OS == 'Lienol' && env.OS_BRANCH == ''
       echo "REPO_BRANCH=21.02" >> $GITHUB_ENV


     - name: coolsnowwolf lede  
       if: env.OpenWtr_OS == 'lede' 
       echo "REPO_URL=https://github.com/coolsnowwolf/lede" >> $GITHUB_ENV
       echo "REPO_BRANCH=master" >> $GITHUB_ENV
		
     - name: 天灵 immortalwrt
     if: env.OpenWtr_OS == 'immortalwrt'   
    echo "REPO_URL=https://github.com/immortalwrt/immortalwrt" >> $GITHUB_ENV   
		if: env.OpenWtr_OS == 'immortalwrt' && env.OS_BRANCH != ''
       echo "REPO_BRANCH=$({{OS_BRANCH}})" >> $GITHUB_ENV
    if: env.OpenWtr_OS == 'immortalwrt' && env.OS_BRANCH == ''
       echo "REPO_BRANCH=openwrt-18.06-k5.4" >> $GITHUB_ENV
