name: Test ssh

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: Start SSH via tmate
        uses: P3TERX/ssh2actions@main
        # Send connection info to Telegram (optional)
        # You can find related documents here: https://core.telegram.org/bots
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}        
